// USERS
export const GET_CURRENT_USER_INIT = "GET_CURRENT_USER_INIT";
export const GET_CURRENT_USER_COMPLETED = "GET_CURRENT_USER_COMPLETED";
export const GET_CURRENT_USER_FAILED = "GET_CURRENT_USER_FAILED";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SIGN_OUT = "SIGN_OUT";

// SIGN IN
export const SIGN_IN_INIT = "SIGN_IN_INIT";
export const SIGN_IN_COMPLETED = "SIGN_IN_COMPLTED";
export const SIGN_IN_FAILED = "SIGN_IN_FAILED";

// SIGN UP
export const SIGN_UP_INIT = "SIGN_UP_INIT";
export const SIGN_UP_COMPLETED = "SIGN_UP_COMPLTED";
export const SIGN_UP_FAILED = "SIGN_IN_FAILED";

// GAMES
export const GET_POPULAR_GAMES_INIT = "GET_POPULAR_GAMES_INIT";
export const GET_POPULAR_GAMES_SUCCESS = "GET_POPULAR_GAMES_SUCCESS";
export const GET_POPULAR_GAMES_FAILED = "GET_POPULAR_GAMES_FAILED";
// export const GET_POPULAR_GAMES = "GET_POPULAR_GAMES";
export const GET_TOP_RATED_GAMES_INIT = "GET_TOP_RATED_GAMES_INIT";
export const GET_TOP_RATED_GAMES_SUCCESS = "GET_TOP_RATED_GAMES_SUCCESS";
export const GET_TOP_RATED_GAMES_FAILED = "GET_TOP_RATED_GAMES_FAILED";
// export const GET_TOP_RATED_GAMES = "GET_TOP_RATED_GAMES";
export const GET_BEST_GAMES_INIT = "GET_BEST_GAMES_INIT";
export const GET_BEST_GAMES_SUCCESS = "GET_BEST_GAMES_SUCCESS";
export const GET_BEST_GAMES_FAILED = "GET_BEST_GAMES_FAILED";
// export const GET_BEST_GAMES = "GET_BEST_GAMES";
